import './App.css';
import Navbar from './components/navbar.jsx';
import Footer from './components/footer.jsx';

function App() {
  return (
    <div className="App">
      <Navbar />
      <p>
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
        1 <br />
      </p>
      <Footer />
    </div>
  );
}

export default App;
